// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARkFrs_f3J0zR6MRmZO4vJtlDcwhQUXRk',
    appId: '1:171260151340:web:8718a38c3e46ea71ca3389',
    messagingSenderId: '171260151340',
    projectId: 'jaya-tirta',
    authDomain: 'jaya-tirta.firebaseapp.com',
    storageBucket: 'jaya-tirta.appspot.com',
    measurementId: 'G-ZP5KD5PZDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF6FbUnTqXQsNBoNS3bEd6SGyD77EH9Ng',
    appId: '1:171260151340:android:77496a5106ec4ab2ca3389',
    messagingSenderId: '171260151340',
    projectId: 'jaya-tirta',
    storageBucket: 'jaya-tirta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyopi_z_e9Nno2AZHDXFPsYKPx_vzBubU',
    appId: '1:171260151340:ios:917f918caa10b7dfca3389',
    messagingSenderId: '171260151340',
    projectId: 'jaya-tirta',
    storageBucket: 'jaya-tirta.appspot.com',
    iosClientId: '171260151340-6tl3cd27r1gf7t7lc6ifgra68lbclv96.apps.googleusercontent.com',
    iosBundleId: 'com.polban.jayatirta',
  );
}
